name: Generate Snake Game from GitHub Contributions

on:
  schedule:
    - cron: "0 0 * * *"  # Her gün saat 00:00'da çalışır
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Platane SNK Action: Yılan oyunu görselini oluştur
      - name: Generate Snake Game from GitHub Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}  # Kullanıcı adı, context ile alınıyor
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Commit ve push işlemi: Üretilen görselleri deponuza ekleyin
      - name: Commit and Push Generated Images
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Add generated snake game images"
          git push https://x-access-token:${{ secrets.MY_GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
